### ISSUE TITLE
Create a user account

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-hub#2]
**User Story:**
As a project owner
I want to create an account linked to my wallet address
So that I can create projects in Grant Hub

**Acceptance Criteria**

GIVEN that I have not connected my wallet on Grant Hub
WHEN I arrive on the landing page
THEN I see a button to "Connect wallet"

GIVEN that I have not connected my wallet on Grant Hub
WHEN I click on "Connect wallet" 
THEN I see options to connect my wallet (i.e Metamask) 

GIVEN that I have connected my wallet on Grants Hub 
WHEN I arrive on the landing page 
THEN I see a "Grant Hub" button that takes me to my dashboard 

**Product & Design Links:**
PRD: https://gitcoin.notion.site/v2-PRD-Grant-Hub-cfae51e50ee74a67ba8776b27e629fdb
Designs: https://www.figma.com/proto/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?page-id=249%3A1000&node-id=334%3A4487&viewport=241%2C48%2C0.09&scaling=scale-down&starting-point-node-id=326%3A4027

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

![Image](https://user-images.githubusercontent.com/26017180/169361084-3508d933-f033-4f3a-9c36-c8785afb6d49.png)

**Comment by schultztimothy** [comment]
@gravityblast actually completed this when setting up the repo! Here is a link to the current site that is deployed with each update to the main branch https://gitcoinco.github.io/grants-hub/
