### ISSUE TITLE
ui bug: incorrect error message on round title

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-hub#254]
**Overview**
The round creation page gives an incorrect error message when you type in a short round title

**Steps To Reproduce**
1. Go to create round page
2. Enter in a round name that is <8 characters
3. Hit next

**Observed  behavior**
The error message says that the title needs to be _less_ than 8 characters

**Expected behavior**
The error message should say that the title needs to be "at least" 8 characters

**Screenshot**
![Image](https://user-images.githubusercontent.com/15041635/184657058-8c1afe9b-0226-4e08-bda1-0ca0b61a6e6c.png)

**Comment by thelostone-mc** [comment]
I noticed this while testing out the flow and fixed the text in 4b85355
