### ISSUE TITLE
fix web3 login on mobile

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-hub#279]
with the new wagmi integration I can't login from mobile browser anymore. 
I tried so far with Metamask mobile on iOS

**Comment by codenamejason** [comment]
![image](https://user-images.githubusercontent.com/9419140/187569181-8ce8925f-bede-4c4f-8e5e-0ab0a70c0a7c.png)

![image](https://user-images.githubusercontent.com/9419140/187569188-e2cb7075-eb8a-4351-aa80-6be4205e38fc.png)

**Comment by codenamejason** [comment]
On Brave and Chrome the MetaMask login only triggers your MM wallet to open and does not trigger a 'connect'

on the staging.granthub.gitcoin.co it will offer the 'connect' button but after you connect it shows only 'Something went wrong error'
