### ISSUE TITLE
Create a project

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-hub#3]
**User Story:**
As a project owner
I want to create a project in Grant Hub
So that I can apply to rounds and receive funding

**Acceptance Criteria**
GIVEN that I have connected my wallet on Grant Hub
WHEN I land on the Grant Hub dashboard 
THEN I see a "Create Project" button

GIVEN that I am on the Grant Hub dashboard 
WHEN I click on the "Create Project" button
THEN I am brought to the project creation page
AND I see fields to enter in my project details (project name, website, description, etc.) 
AND I see a button to "Exit" 
AND I see a button to "Save & Publish" 

GIVEN that I am on the project creation page and have entered values in all the fields
WHEN I click on the "Exit" button 
THEN any changes I have made will NOT be saved
AND I am taken back to the Grant Hub dashboard 

GIVEN that I am on the project creation page and have entered values in all the fields
WHEN I click on the "Save & Publish" button 
THEN I receive a popup requesting my on-chain signature 
AND my project is saved on IPFS 
AND my project is published on-chain 
AND I am taken back to the Grant Hub dashboard 

**Product & Design Links:**
PRD: https://gitcoin.notion.site/v2-PRD-Grant-Hub-cfae51e50ee74a67ba8776b27e629fdb
Designs: https://www.figma.com/proto/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?page-id=249%3A1000&node-id=334%3A4487&viewport=241%2C48%2C0.09&scaling=scale-down&starting-point-node-id=326%3A4027

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**

![Image](https://user-images.githubusercontent.com/26017180/169363233-a08b4101-55f5-42d2-be7a-5013524c124e.png)

![Image](https://user-images.githubusercontent.com/26017180/169363267-efa5fcdb-1102-4271-8a58-241bee638fab.png)

**Comment by schultztimothy** [comment]
I misunderstood this ticket a bit and didn't realize it was just scoped to publishing the data to IPFS 😄. Good new is that this should make the rest of the tickets easier since it includes a possible implementation of the grant contract
