### ISSUE TITLE
general: Add Customer Support flow

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#304]
**User Story**

As a project owner, 
I want to know how to learn more about Grants Hub or contact support
so that if I have questions I can get them answered

**Acceptance Criteria**

_Nav bar_
GIVEN that I am in Grants Hub 
WHEN I look at the nav bar
THEN I see a button for Help 

GIVEN that I click on "Help" 
WHEN I look at the page
THEN I see a dropdown with options to go to Grants Hub Guide, Contact Support, Give Feedback, Developer Docs

_Create Project Flow_
Given that I am on the Create or Edit Project page 
WHEN I look at the page
THEN I see a message saying "Need Help? Check out the Grants Hub Guide" which links me to the Grants Hub Guide

_Application Flow_
Given that I am on the Application page 
WHEN I look at the page
THEN I see a message saying "Need Help? Check out the Grants Hub Guide" which links me to the Grants Hub Guide

_Empty State_
Given that I am on the My Projects page and I have created no projects
WHEN I look at the page
THEN I see a message saying "Learn more." which links me to the Grants Hub Guide

**Links**
* Grants Hub Guide: https://support.gitcoin.co/gitcoin-grants-protocol
* Contact Support: https://support.gitcoin.co/
* Feedback form: https://forms.gle/XxqRtP1WbaL3cLNA8
* Developer Docs: https://app.gitbook.com/o/Aqbtj6s4OkLaygileCka/home

**Designs**

* [Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2557%3A17537) (under "Final - Support v2"):

**Comment by michellema1208** [comment]
@gravityblast @DanieleSalatti @codenamejason looking at the sticky footer here, do we have the final links for what would be the public-facing Github repo for Grant Hub and final link for documentation? I know for documentation, Tim had started a Gitbook but it was just in his name. 

If there are links ready, can you share them here?

**Comment by codenamejason** [comment]
https://github.com/gitcoinco/grant-hub

Need to set up a Grant Hub Gitbook account still.
