### ISSUE TITLE
round application page: redirect to project creation if the users doesn't have projects yet

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-hub#319]
**Tasks**
- [ ] If a user with NO projects lands on application landing page, button should say "Create a project" instead of "Apply to round" and it should redirect to the create a project page

**Comment by michellema1208** [comment]
### ✅ Status Update: Moving to "Ready for Deployment" 

@codenamejason (cc: @gravityblast) I just tested this, and it looks like it's working for me! Kudos to you and @gravityblast for the fix here!
