### ISSUE TITLE
application: the application questions do not match application schema in Round Manager

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#355]
Application link: https://staging.granthub.gitcoin.co/#/chains/5/rounds/0xd0ad4e7fb437663f1a3d8cb54dec9ec6f3d4bde2/apply

Some discrepancies (from Round Manager -> Grant Hub Application): 

- Email address -> Email 
- Funding Sources -> Funding Source
- 2022 Profit -> Profit2022

We should keep the same application questions that were provided by the Round Manager

**Comment by codenamejason** [comment]
It looks like we are using the application questions from the metadata @michellema1208 

`label={input.question}` where input is an item from the schema array

<img width="357" alt="Screen Shot 2022-09-22 at 1 32 16 PM" src="https://user-images.githubusercontent.com/9419140/191813763-0fb90385-0a9e-4052-902f-78fc16230da9.png">

**Comment by michellema1208** [comment]
@codenamejason just an FYI that this is working now! Will move this to done :) 

![Image](https://user-images.githubusercontent.com/26017180/194131966-19b44860-25b9-4e4f-b2aa-7ef1c155a952.png)
