### ISSUE TITLE
create/edit project: optional questions should have "Optional" tags

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#359]
**User Story**
As a project owner, 
I want to see which questions are optional vs. required when creating a project
so that I know what questions I need to fill out in order to move to the next step

**Acceptance Criteria**
- On create project and edit project pages, optional questions (banner, logo, twitter, github, github org) should be marked as "Optional"

**Comment by codenamejason** [comment]
@michellema1208 @willsputra 

How should this look? Here is an example of using same placement as `*Required`

<img width="618" alt="Screen Shot 2022-09-22 at 1 42 55 PM" src="https://user-images.githubusercontent.com/9419140/191815683-a90baafc-e5a3-4eda-a7d1-98d9deddcfda.png">

**Comment by michellema1208** [comment]
@codenamejason per @willsputra's designs, I think the grey font color for Optional would look better for contrast! 

If this is a quick fix, let's merge it and update, but if not this ticket can wait - it's marked as "Secondary"

![Image](https://user-images.githubusercontent.com/26017180/191845248-a1538436-34be-48f7-98c5-e8090aac096d.png)
