### ISSUE TITLE
application: after applying to a round, redirect to Project Details page

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#366]
**User Story**
As a project owner, 
I want to go to the project details page for the project I just submitted
so that I can see my application status 

Note: The "My Applications" section will live on the Project Details page

**Acceptance Criteria**

GIVEN that I just submitted my application 
WHEN I look at the page 
THEN I see that I have been redirected to the Project Details page 

Note: When the application is processing, STAY on application page, do not take user to new page

**Comment by codenamejason** [comment]
@michellema1208 going to create a new ticket/issue for the success banner
