### ISSUE TITLE
edit project: if I don’t upload a new logo/banner, the preview step still shows the default images

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#374]
From @willsputra: On Edit Project, if I don’t upload a new logo/banner, the preview step still shows the default images

![will1](https://user-images.githubusercontent.com/26017180/191627834-11884a36-35c8-4317-94fc-b00f6ffba718.png)
![will2](https://user-images.githubusercontent.com/26017180/191627841-29ce2db9-600c-4b95-b968-f046e72162a2.png)

**Comment by michellema1208** [comment]
@willsputra can you share steps on how to reproduce this issue? I just tried editing a project I had created that didn't have logo/banner, but didn't have an issue with seeing default images on preview.

Also, are you on staging or production? If on production, I wonder if this will be addressed by Jason's upcoming deploys.

**Comment by willsputra** [comment]
@michellema1208 it was on staging! just tested it again, seems like it works correctly now. I'm seeing the right images on the project preview page.
<img width="1614" alt="image" src="https://user-images.githubusercontent.com/19514207/191754196-d37dc8cb-0f1c-46bb-b942-615c81062ce9.png">
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/19514207/191754222-87270543-736b-40e4-9cec-1ada193d9ce7.png">

**Comment by michellema1208** [comment]
Awesome thanks Will for confirming! Am going to close this ticket and move it to archives
