### ISSUE TITLE
Set up Datadog Monitoring

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-hub#378]
**User Story**
As a Grant Hub Engineer, 
I want to setup datadog monitoring serivces
so that I am aware of when the app is down and needs support

**Notes**: 
setup: datadog RUM
explore: https://docs.datadoghq.com/synthetics/

round manager implementation: https://github.com/gitcoinco/grants-round/pull/446

**Comment by DanieleSalatti** [comment]
ENV vars are set on Staging

Prod coming up next

**Comment by DanieleSalatti** [comment]
ENV vars set in Prod as well

Missing deployment of #481
