### ISSUE TITLE
Apply to round link defaulting to mainnet OP when on testnet

### ISSUE THREAD

**Issue by codenamejason** [gitcoinco/grants-hub#379]
When I am on my projects page and click the apply to round button in either the modal or on the alert/banner it is sending me to OP mainnet when I am on goerli testnet.

Expected behavior: to link to proper round for that chain you are on.

<img width="1681" alt="Screen Shot 2022-09-22 at 11 00 03 AM" src="https://user-images.githubusercontent.com/9419140/191782737-390d3ffb-9d61-4fce-8038-c711ddba97f9.png">

**Comment by michellema1208** [comment]
hey @codenamejason - I haven't been able to reproduce this issue - when I am on Goerli and go to apply for a round, it stays on the same chain (testing on prod as well). Is this still happening on your side? If so, can you record a Loom and share the behavior?
