### ISSUE TITLE
verification: handling for use case when user enters no socials or partial socials

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#404]
**User Story** 
As a project owner, 
I want the option only verify the socials I have inputted
so that I don't get confused and think that I need to verify all socials 

**Acceptance Criteria**
GIVEN I am creating a project 
WHEN I look at the page 
THEN I see questions for Project Name, Project Website, Project Logo, Project Banner, Project Description 

GIVEN that I have filled out the above questions
WHEN I hit "Next" and advance to the Verification Page
THEN I see a Verification Page with questions for Project Socials (Project Twitter Account, Your Github Username, Your Github Organization) 
AND the option to "Skip" this page 

GIVEN that I am on the Verification Page
WHEN I start to enter an answer to either of the Project Socials questions
THEN I see the "Skip" button update to "Next" 

GIVEN that I am on the Verification Page
WHEN I start to enter an answer to the Project Twitter Account question
THEN I see the option to Verify 
AND I see a tooltip with information about verification (see copy for tooltip below) 

GIVEN that I am on the Verification Page
WHEN I start to enter an answer to Your Github Username and Project Github Organization
THEN I see the option to Verify
AND I see a tooltip with information about verification 
(Note: I only see the option to Verify after I start to enter answers to _both_ Github Username & Project Github Organization questions) 

GIVEN that I successfully verify my Project Socials
WHEN I look at the Verification page
THEN I see the verification badge next to the socials that I have successfully verified 

GIVEN that I successfully verify my Project Socials
WHEN I hit "Next" and advance to the Project Preview page
THEN I see verification badge next to the socials that I have successfully verified 

_Error Use Case_
GIVEN that I fail to verify my Project Socials 
WHEN I look at the page
THEN I see an error message around my error use case 

**Notes**
* On the Verification Page, when there are no answers, the bottom-right button should say "Skip"
* On the Verification Page, once the user starts to enter an answer to either of the Project Socials questions, then the bottom-right button should update to say "Next" 
* Users can move forward even if they have not verified their socials 
* The copy of the tooltip should say the following: 
![Image](https://user-images.githubusercontent.com/26017180/196470180-beb18691-0ef2-4220-9c44-fb5a5827cac8.png)

Error Use Cases (see 
* Your Twitter username does not match 
* Your Github username does not match 
* Your Github account is private in the Organization that you provided 

For Twitter username does not match (same applies for Github - just swap out Twitter for Github)
![Image](https://user-images.githubusercontent.com/26017180/196472536-0cbee295-bfb6-4ff5-a9ef-223064f03b52.png)

Your Github account is private in the Organization that you provided 
![Image](https://user-images.githubusercontent.com/26017180/196472703-95c050e3-4dec-4bcc-87b3-6081456ab641.png)

**Product & Design Links:** 
* [Figma link](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2557%3A17537)
* Loom Recording for User Flow: https://www.loom.com/share/42ae1b4402324a579271a60ce85dd712

**Tech Details**: 
- [x] Update error message for Github failures to a generic error message (see copy in thread on Discord) 
- [x] Log errors on Datadog so we can better identify what caused the failure -> will have more descriptive error messages in the future

**Open Questions**: 
* N/A

**Comment by willsputra** [comment]
looking good @DanieleSalatti ! just a few feedback cc @michellema1208 

- [x] the Verify button is hidden by default for github, but visible for twitter (but greyed out). could we hide both by default, and only show them when the user types?
- [x] do we have the info tooltip?
- [x] once we have the tooltip, we don't need the small description text ("Connect your ... to verify (Optional)")
- [x] update the placeholder texts to match the Figma file


here's what I saw btw on staging


![Image](https://user-images.githubusercontent.com/19514207/200370531-66815137-33e7-413f-9a1f-a9acdc19434b.png)

**Comment by DanieleSalatti** [comment]
Also swapped the position of the two blocks as per Figma (i.e. Twitter is at the top now)

**Comment by DanieleSalatti** [comment]
Turns out I already added Datadog logging and metrics...

About to submit a PR

**Comment by DanieleSalatti** [comment]
PR #543
