### ISSUE TITLE
project details: add MVP application status

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#422]
**User Story** 
As a project owner, 
I want to confirm whether or not I've applied to a round 
so that I know my application has been received 

**Acceptance Criteria**
GIVEN that I just applied to a round 
WHEN I am redirected to the Project Details page  
THEN I see the "My Applications" section with my application status 

The "My Applications" section should include: 
* Heading that reads "My Applications" 
* Program Name
* Round Name
* Round start and end dates (not application dates) 
* How to reach out to Grant Round support team 

**Product & Design Links:** 
* [Figma link](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2557%3A17537)
<img width="712" alt="Screen Shot 2022-10-02 at 11 57 48 AM" src="https://user-images.githubusercontent.com/26017180/193463617-5debcc2a-2d76-424e-ba09-2a997c13933e.png">

**Tech Details**: 
* N/A 

**Open Questions**: 
* N/A

**Notes/Assumptions**: 
* The text and link to contact customer support will need to come from round metadata (Round Manager Dependency)

**Comment by codenamejason** [comment]
@michellema1208 I wanted to call out that the details page doesn't really line up with the Figma. i.e. the banner image doesn't fill the width.

<img width="1198" alt="Screen Shot 2022-10-05 at 12 20 43 PM" src="https://user-images.githubusercontent.com/9419140/194111389-28aa07fd-db78-4d6e-a8ac-05129905db7b.png">

**Comment by michellema1208** [comment]
@codenamejason yes, great catch! This was actually something that @willsputra called out and I was tracking in https://github.com/gitcoinco/grants-stack/issues/1746, but we put it in Secondary because it wasn't launch-blocking. 

I see that without the banner image filling out the full width, the application status box looks out of place. So @codenamejason if it would be quick for you to make the change to get banner image to fill out full width along with this ticket, I think that makes sense! And we can take it out of the other ticket :)

**Comment by codenamejason** [comment]
@michellema1208 here is example

<img width="1213" alt="Screen Shot 2022-10-05 at 12 37 13 PM" src="https://user-images.githubusercontent.com/9419140/194114456-1713fc68-1497-4c76-a2e7-08168261a89d.png">

**Comment by michellema1208** [comment]
@codenamejason yeah this looks great to me! I think the spacing between the links like website, twitter, dates looks a bit tighter than your first screenshot? But otherwise, the full width banner looks great :) / placement of applications card looks good too

**Comment by codenamejason** [comment]
@michellema1208  @willsputra question on the "My Applications" location

Can we put it outside the card bc there may be many cards and then we have "My Applications" showing in each one when I think it should just be the one time with the list of cards below. WDYT?

<img width="408" alt="Screen Shot 2022-10-06 at 5 21 43 PM" src="https://user-images.githubusercontent.com/9419140/194421104-b8598b7f-9bbd-4b84-be35-744fe2a73913.png">

**Comment by michellema1208** [comment]
ooh @codenamejason I actually really love that thinking - awesome catch Jason! I think that makes total sense - over time, projects will have more than one application that they'll want to check on. This feels within the domain of the Design space, so let's wait until @willsputra is back online to confirm. 

One other thing - per the "view application" button - actually viewing the application you submitted in read-only state is not in scope for this ticket. If you already built it, incredible -- we can roll with it. But if not, let's keep the overall structure that Will had in his designs: 

- Status should say "Applied" not pending 
- No "View Application" button, just the round details

<img width="712" alt="applystatus" src="https://user-images.githubusercontent.com/26017180/194422004-becc209c-4c14-43ad-a758-c0207eb077dc.png">

**Comment by willsputra** [comment]
> @michellema1208 @willsputra question on the "My Applications" location
> 
> Can we put it outside the card bc there may be many cards and then we have "My Applications" showing in each one when I think it should just be the one time with the list of cards below. WDYT?
> 
> <img alt="Screen Shot 2022-10-06 at 5 21 43 PM" width="408" src="https://user-images.githubusercontent.com/9419140/194421104-b8598b7f-9bbd-4b84-be35-744fe2a73913.png">

I love the idea! yes, it makes sense to put "My Applications" outside the card since there might be multiple applications in the future. let's do it :)

**Comment by codenamejason** [comment]
Thanks @michellema1208 @willsputra 

Here is an example with hardcoded values.

<img width="1172" alt="Screen Shot 2022-10-07 at 9 42 12 AM" src="https://user-images.githubusercontent.com/9419140/194567717-f0f66fe0-a894-40ed-b102-e778d8444611.png">

**Comment by codenamejason** [comment]
@willsputra I also need a mobile view, just thought of it 📲

**Comment by codenamejason** [comment]
This is the latest 🫣

<img width="457" alt="Screen Shot 2022-10-07 at 11 08 00 AM" src="https://user-images.githubusercontent.com/9419140/194586656-d3f9a5ea-c383-48a9-8acb-4f49bd81150c.png">

**Comment by willsputra** [comment]
@codenamejason looking good! mobile view here:
https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A19114
