### ISSUE TITLE
create/edit project: add HTTPS to website URLs by default 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#432]
**User Story**
As a project owner, 
I want to be able to share the website of my project without having to manually add HTTPS
so that I don't get stuck trying to validate my website URL

**Acceptance Criteria**
GIVEN that I am on the Create or Edit Project form 
WHEN I look at the "Project Website" question
THEN I see a "https://" header next to the answer

GIVEN that I have added a website URL in my project form 
WHEN the project is created 
THEN the website link on my project profile takes me to my project website 

**Notes**: 
* This should apply on both the Create Project form and 
* We will want to make a UI change to the Project Website question to visually show "https://" (see designs below)

**Tech Details**
We can simply add the `https://` prefix before submitting the project, and remove it before setting the projectForm data for the form.

**Designs ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A10232))**
<img width="715" alt="Screen Shot 2022-10-13 at 11 10 55 AM" src="https://user-images.githubusercontent.com/26017180/195637308-72ed648c-28fe-482c-9947-e2b43121e23f.png">

**Comment by michellema1208** [comment]
@gravityblast qq: why would we remove the `https://` prefix before setting the projectForm data for the form?

**Comment by gravityblast** [comment]
@michellema1208 @ghostffcode we don't want the use to write https, so when the form is submitted we add it the the url.
when we show again the form, we should remove it so that we continue to show the url in the field without the https prefix, and we add it again when it's submitted.

**Comment by michellema1208** [comment]
@gravityblast ok got it, yes that makes sense!
