### ISSUE TITLE
application: disable the LIT protocol encryption Metamask/WalletConnect prompt if user is already connected

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#451]
**User Story**
As a project owner 
I want to submit an application without having to connect my wallet if I'm already connected 
so that I have less steps to finish 

**Acceptance Criteria**
GIVEN that my wallet is already connected
WHEN I submit an application
THEN I do not see a prompt from LIT Protocol to connect my wallet again 

**Tech Details**
+ @gravityblast to add any Engineering details here

**Comment by ghostffcode** [comment]
Lit protocol has no input for custom provider/signer so the modal is needed to connect to a wallet.
