### ISSUE TITLE
general: update logic for "apply to round" banner

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#452]
**User Story**
As a project owner, 
I want to be able to revisit an application link 
so that I can submit an application at any time 

**Acceptance Criteria**
GIVEN that I have arrived at Grant Hub via an application link
WHEN I navigate away from the application before submitting  
THEN I see an "Apply to Round" banner on the home page that will take me back to my application 

GIVEN that I see the "Apply to Round" banner 
WHEN I look at the banner 
THEN I see the Program and Round name of the round I am applying to

GIVEN that I have successfully applied to a round
WHEN I go to the Grant Hub home page 
THEN I no longer see the "Apply to Round" banner 

**Notes:** 
- Existing users should not see the "Apply for a Round" modal -> this should only be for new users (See: https://github.com/gitcoinco/grant-hub/issues/311) 
- If after applying to a round, a user decides to apply to another round, then after they visit the new application link and navigate back to Home, the banner should be there again, but this time for the new round (this use case is low likelihood, but would be good to support) 

**Designs** ([Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=2188%3A10232)) 

**Apply for Round banner** (this already exists in the app today) 
![Image](https://user-images.githubusercontent.com/26017180/194316800-de3373c9-ed97-4b05-99c6-96422f1a8a3b.png)

**Comment by ghostffcode** [comment]
@michellema1208 @gravityblast how are we feeling about this ticket still? I overhead about it being in localStorage and was just temporarily disabled (I could be wrong though). What's the best way forward on it?
