### ISSUE TITLE
multichain: be able to load all of my projects across all supported networks (part II)

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#533]
**Note**: this ticket is Part II of the epic to the be able to load projects across all networks. For Part I: https://github.com/gitcoinco/grant-hub/issues/587

**User Story**
As a project owner, 
I want to see and access all of my projects across all chains 
so that I don't have to create duplicate projects for each chain

**Acceptance Criteria**
GIVEN that I am on the "My Projects" page 
WHEN I look at the page
THEN I should see all of the projects I have created across different networks

**Notes:** 
* Should make sure to test this ticket is working on My Projects page and Application page

**Designs**
* [Figma](https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Grant-Hub---Wireframes?node-id=3112%3A21936)

**Engineering Notes**
* Update our "loadProjects" function to load projects from all the supported networks, instead of using the current network from the user's wallet provider

**Comment by DanieleSalatti** [comment]
PR #622
