### ISSUE TITLE
bug: application on fantom testnet errors on encryption step 

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#542]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by codenamejason** [comment]
Error from console:

![Screenshot 2022-11-07 at 3 09 32 PM](https://user-images.githubusercontent.com/9419140/200433746-f5dfd3fa-1660-4e6f-b4e6-ffef811714e1.png)
