### ISSUE TITLE
Research subgraph options for project registry

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#55]
Context: https://discord.com/channels/562828676480237578/962026258273804398/979047556413800508

**Comment by schultztimothy** [comment]
Pricing
- The hosted graph service is free and I believe will always be
- The decentralized protocol charges on a per query basis. 
    - Consumers are the end-users of The Graph that query subgraphs and pay query fees to the Indexers, Curators and Delegators. Consumers are likely to be developers or projects themselves that cover query fees for their applications as they would AWS or cloud service costs. However, some applications will pass on query fees to users or bundle the cost in product fees. Consumers will pay for query fees via “gateways” or wallets that will be built on top of open source contracts in The Graph Network.

Decentrazlied Network:
- It is not currently possible to index data from IPFS on the decentralized network - https://thegraph.com/docs/en/hosted-service/migrating-subgraph/

Unified Schema:
- Currently [federation](https://www.apollographql.com/docs/studio/federated-graphs/) is not supported: https://thegraph.com/docs/en/developer/developer-faq/#21-is-this-possible-to-use-apollo-federation-on-top-of-graph-node
- It is possible to stitch together schemas - ie create a single queryable endpoint that can query across the grant-hub graphs that are deployed across L2s

Relationships:
- They support one to one, one to many and many to many relationships. I believe the [many to many](https://thegraph.com/docs/en/developer/create-subgraph-hosted/#many-to-many-relationships) relationship would work for the use case discussed in the thread
- I started on a [schema](https://thegraph.com/hosted-service/subgraph/schultztimothy/grantub?selected=playground) that maps the owners to what projects they have created as well as a mapping the owners that exist on a particular project

Factory Contracts:
- These are handled through what they call [datasource templates](https://thegraph.com/docs/en/developer/create-subgraph-hosted/#data-source-templates)
- Its what is being used by uniswap to create indexes for the arbitrary amount of [Pools](https://etherscan.io/address/0x5777d92f208679db4b9778590fa3cab3ac9e2168#events) that are being created by their [factory](https://etherscan.io/address/0x1f98431c8ad98523631ae4a59f267346ea31f984)

Cross Network:
- It does not look like it is possible to index data across networks/L2s
- They do have a [network](https://thegraph.com/docs/en/hosted-service/deploy-subgraph-hosted/#deploying-the-subgraph-to-multiple-ethereum-networks) configuration that is used to deploy the same graph across multiple networks

**Comment by schultztimothy** [comment]
Here is a WIP implementation of adding a subgraph for the grants hub: https://github.com/gitcoinco/grants-hub/tree/subgraph-research it was used to generate: https://thegraph.com/hosted-service/subgraph/schultztimothy/grantub?selected=playground

**Comment by michellema1208** [comment]
@schultztimothy what was the final recommendation here? /how is the team is moving forward with implementing subgraph(s) for the project registry? 

Will update/close out this ticket depending on where things landed
