### ISSUE TITLE
landing page: update Gitcoin text logo color and size

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#569]
**Tasks**

- [ ] Update Gitcoin text logo to font color "grey-500" to match "Grants Hub" text
- [ ] Increase Gitcoin logo size to 16px height

**Comment by codenamejason** [comment]
@michellema1208 

![Image](https://user-images.githubusercontent.com/9419140/204906709-aa55a2bb-06db-4a3c-9331-d64725085505.png)

This is grey-500, the Figma shows black for the color of Grants Hub and font is even different.

Figma:


![Image](https://user-images.githubusercontent.com/9419140/204906994-baa46217-d70f-4d30-b075-363be6fadc40.png)

**Comment by codenamejason** [comment]
Is this what is needed to be darker?


![Image](https://user-images.githubusercontent.com/9419140/204907541-8b6bc89f-45c0-42ef-93aa-a0cff7105aac.png)
