### ISSUE TITLE
multichain: add chain id in the project detail URL (part I) 

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-hub#587]
**Note**: this ticket is Part I of the epic to the be able to load projects. For Part II: https://github.com/gitcoinco/grant-hub/issues/533

**User Story**

**Acceptance Criteria**

**Engineering Notes**
In the current implementation the URL for a project is in the following format:

`/projects/PROJECT_ID`

We want to add the chain ID to prepare the system to be multi-chain with the following URL:

`/chains/CHAIN_ID/projects/PROJECT_ID`

In our app state we store the projects with numeric ids. We should change it probably to a string containing chainID and projectID to be able to always have unique IDs  like `CHAIN_ID:PROJECT_ID`.

If the URL contains chainID `A` and the user is on chainID `B`, we won't be able to find `A:PROJECT_ID` in our state, and we can display a message saying that the user is on the wrong network or that the project has not been found. 

With one of the next user stories, we will actually load the project anyway using a different web3 provider based on the chainID specified in the URL.

**Comment by michellema1208** [comment]
Notes: upon working on this ticket, we've found that this ticket was probably closer to 2 story points, because it touched many parts of the code and needed to be thoroughly tested.
