### ISSUE TITLE
[tech] UI work > Toast component

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#59]
Confirmation pop-up at the bottom of the page

**Comment by schultztimothy** [comment]
@michellema1208 @willsputra I added some additional messages and an error state to the transaction process that were not in the mocks, but it seemed needed to inform the user of what stage their transaction is in. I added screenshots below. Just let me know if I should take them out



![Image](https://user-images.githubusercontent.com/6887938/174914753-f0a1ce36-e581-4c6d-8f41-327c3f3881a1.png)
![Image](https://user-images.githubusercontent.com/6887938/174914755-8efebb08-6ddf-4405-8970-49f47807bb4a.png)
![Image](https://user-images.githubusercontent.com/6887938/174914752-d1d3661e-a271-4c2b-b2f3-dbd81749e4ca.png)
![Image](https://user-images.githubusercontent.com/6887938/174914756-f292af6e-ff5b-4be5-a7f9-f9d6830eec0e.png)
![Image](https://user-images.githubusercontent.com/6887938/174914754-d41dae9c-1582-4eff-94b5-78b905e66d6d.png)

**Comment by michellema1208** [comment]
These look great! Two notes/questions: 

- For "Your Transaction is Processing" - can we do lowercase "transaction" and "processing" ? 
- Is the "please confirm your transaction" for when the user is on the second screen of the Metamask wallet, which asks for confirmation? 
- For "project created" and "wallet connected", can we make those green to indicate action successful?
