### ISSUE TITLE
bug: twitter verification is not shown in the project edit page

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-hub#595]
Steps:
* create or edit a project and verify twitter
* save the project
* go to the project details page (it should show the verified badge on twitter)
* go to the edit page of the project and click on next
* at this point since twitter it's already verified we should show:

<img width="714" alt="Screenshot 2022-11-21 at 14 38 56" src="https://user-images.githubusercontent.com/1059/203070060-0cbaa718-64be-44c9-966d-c3c824e76b52.png">

but the verified badge is not shown:

<img width="708" alt="Screenshot 2022-11-21 at 14 39 10" src="https://user-images.githubusercontent.com/1059/203070131-1141cc08-d251-4d55-8727-e6b1dee2d84e.png">

We should probably change the following line in `Twitter.tsx`

```
  useEffect(() => {
    setComplete(false);
  }, [props.formMetaData.projectTwitter]);
```

to something like `setComplete(verified)`, where `verified` is checking if we have a verifiable credential in  state.grantsMetadata for that project, and then calling `REACT_APP_PASSPORT_IAM_URL` to verify it. This part is already implemented and only used in the `listenForRedirect` function.

**Comment by michellema1208** [comment]
@gravityblast can you check if this is also happening with Github?
