### ISSUE TITLE
bug: fix round  landing page styles for mobile

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-hub#601]
**Problem:** The round landing page on mobile is missing margins and looks broken. 

**Tasks**
- [x] Add 16px margins so it's aligned to the margins in nav
- [x] Make sure the Apply button is not cut off 

<img width="442" alt="Screenshot 2022-11-21 at 22 00 59" src="https://user-images.githubusercontent.com/1059/203157568-9eee10fb-c5cc-40a2-9c7a-29374fee92ff.png">

**Comment by willsputra** [comment]
just need to add some margins and make sure the Apply button is not cut off I think. what do you think? @gravityblast @michellema1208
