### ISSUE TITLE
create project: update project creation processing modal

### ISSUE THREAD

**Issue by gravityblast** [gitcoinco/grants-hub#605]
conversation: https://discord.com/channels/562828676480237578/1044374439502037132/1044374442798747658

**Tasks**
- [ ] Add a new step for wallet signature
- [ ] Add a delay for when we've reached the redirecting step

**Comment by 0xKurt** [comment]
![Image](https://user-images.githubusercontent.com/22886639/208129184-dcec711c-a75c-47ed-ad5e-fe537eec7fa4.png)
