### ISSUE TITLE
repo refactoring: migrating the graph folder

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#756]
Context: https://www.notion.so/gitcoin/Rename-Guide-4a0a9aeb0b744e75a8490ba9bf4080fc

The goal of this task is to simply migrate the graph from grants-hub into round-manager as is with little changes.
We will have a follow up task which looks at combining the graph into 1.
This also means we'd have to move the existing graph folder to it's subfolder

Tasks
- [ ] move existing graph folder in grant-round to new subfolder /packages/graph/round
- [ ] move the existing graph folder from grant-hub in grant-round to new subfolder /packages/graph/project-registry

**Acceptance Criteria**

- Ensure this is the new directory structure 

```
|---- packages
        | ---- graph
                 | ---- round
                 | ---- project-registry 
```

- Validate if both graph compiles and can be redeployed on the goerli 
- Ensure data can queried from the subgraph

**Comment by DanieleSalatti** [comment]
Working on fixing the GitHub workflows
