### ISSUE TITLE
[Path to prod] Ensure sufficient data is emitted from events for us to index on to the graph

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grants-hub#92]
- [ ] Verify that we get ownership transfer events

**Comment by schultztimothy** [comment]
Theres another technique to capturing state updates where you get state from function calls. You have access to any parameters that are passed to the function as well as and variables that are returned from the function: https://thegraph.com/docs/en/developer/create-subgraph-hosted/#call-handlers
